### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by tdwilli1** [Smurf-IV/Elucidate#93]
I can't extract the installer from the zip file. It errors out with 0x80004005.

**Comment by Smurf-IV** [comment]
Just tested it (Note the timestamp on the zip file after downloading it)
And it appears to be okay.
![image](https://github.com/Smurf-IV/Elucidate/assets/2418812/e20d440e-f3b0-45e0-849f-424803802b23)

**Comment by tdwilli1** [comment]
Just tried again. Same error. Did you actually try to extract it?

![image](https://github.com/Smurf-IV/Elucidate/assets/49125040/2972aeae-1d07-4a61-9e10-3f335ab4945b)

**Comment by Smurf-IV** [comment]
> Just tried again. Same error. Did you actually try to extract it?

Yes, That's why I showed both files with the timestamps to show that the extract date is the same as when I posted.
Judging by the shape of your windows, I would guess you are using a Windows 11 variant.
It has some features / bugs I was not happy with, so I went back to windows 10.

Can you install 7zip and see if it can extract the file ?

**Comment by tdwilli1** [comment]
7zip worked, thank you.

**Comment by Smurf-IV** [comment]
Another nail in the coffin of windows 11 !
